version: "3.8"

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        env_file:
            - ./Configuration/mongodb.env
        volumes:
            - mongodb:/data/db
            - mongoconfig:/data/configdb
        ports:
            - 27017:27017
        networks:
            - classes_net

    ngrok:
        image: ngrok/ngrok:latest
        container_name: ngrok
        restart: unless-stopped
        command: ["start", "--all", "--config", "/etc/ngrok/config/ngrok.yml"]
        volumes:
            - ./Configuration/ngrok.yml:/etc/ngrok/config/ngrok.yml
        ports:
            - "4040:4040"
        networks:
            - classes_net

    classes:
        image: classes.api
        container_name: classes
        build:
            context: .
            dockerfile: Classes.Api/Dockerfile
        ports:
            - "4000:4000"
            - "4001:4001"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:4000
        networks:
            - classes_net

volumes:
    mongodb:
    mongoconfig:

networks:
    classes_net:
        driver: bridge
